### ISSUE TITLE
cm-beetle의 healthcheck가 unhealthy로 나옴.

### ISSUE THREAD

**Issue by MZC-CSC** [cloud-barista/cm-mayfly#22]
docker-compose.yaml의 healthcheck 조건
```
    healthcheck: # for CM-Beetle
      test: [ "CMD", "curl", "-f", "http://localhost:1323/beetle/readyz" ]
      interval: 1m
      timeout: 5s
      retries: 3
      start_period: 10s
```

제공된 [docker-compose](https://github.com/cloud-barista/cm-beetle/tree/main/deployments/docker-compose)에서는 curl로 healthcheck를 하고 있지만 docker 이미지에 curl이 포함되어 있지 않음.
```
$ docker exec -it cm-beetle curl
OCI runtime exec failed: exec failed: unable to start container process: exec: "curl": executable file not found in $PATH: unknown
```

**Comment by MZC-CSC** [comment]
curl이 포함되어 있지 않아서 mayfly 방식으로 변경하고 포트를 텀블벅의 1323에서 비틀의 8056으로 변경 함.

```
    volumes:
      - ./tool/mayfly:/app/tool/mayfly

    healthcheck: # for CM-Beetle
      test: [ "CMD", "/app/tool/mayfly", "rest", "get", "http://cm-beetle:8056/beetle/readyz" ]
      #test: [ "CMD", "curl", "-f", "http://localhost:1323/beetle/readyz" ]
      interval: 1m
      timeout: 5s
      retries: 3
      start_period: 10s
```
