### ISSUE TITLE
apache-airflow security vulnerability and docker-compose-related

### ISSUE THREAD

**Issue by MZC-CSC** [cloud-barista/cm-mayfly#33]
@ish-hcc
cm-cicada의 [docker-compose.yaml](https://github.com/cloud-barista/cm-cicada/blob/main/docker-compose.yaml)를 참고해서 mayfly의 conf에 _airflow 폴더를 복사해서 cm-cicada 관련 서비스에 아래처럼 사용하고 있습니다. (참고 #17 )
```
  # cm-cicada
  # https://github.com/cloud-barista/cm-cicada
  # https://hub.docker.com/r/cloudbaristaorg/cm-cicada
  cm-cicada:
    #image: cloudbaristaorg/cm-cicada:0.2.0
    image: cloudbaristaorg/cm-cicada:edge
    container_name: cm-cicada
    restart: always
    ports:
      - "8083:8083"
    volumes:
      #- ./conf/cm-cicada/conf:/root/.cm-cicada/conf:rw
      - ./tool/mayfly:/app/tool/mayfly
      - ./conf/cm-cicada/conf:/conf:rw
      - ./conf/cm-cicada/_airflow:/_airflow:rw
      - ./data/cm-cicada/CM-CICADA.db:/CM-CICADA.db:rw
    healthcheck:
      test: [ "CMD", "/app/tool/mayfly", "rest", "get", "http://cm-cicada:8083/cicada/readyz" ]
      interval: 10m
      timeout: 5s
      retries: 3
      start_period: 10s
    #network_mode: "host"

  # airflow-redis
  # used by cm-cicada
  # https://github.com/cloud-barista/cm-cicada/blob/main/_airflow/docker-compose.yml
  airflow-redis:
    container_name: airflow-redis
    image: redis:7.2-alpine
    command: redis-server --requirepass airflow_pass --port 6379
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 30s
      retries: 50

  # airflow-mysql
  # used by cm-cicada
  # https://github.com/cloud-barista/cm-cicada/blob/main/_airflow/docker-compose.yml
  # ./conf/_airflow/create_airflow_db.sql : https://github.com/cloud-barista/cm-cicada/blob/main/_airflow/create_airflow_db.sql
  airflow-mysql:
      container_name: airflow-mysql
      image: mysql:8.0-debian
      cap_add:
        - SYS_NICE
      restart: always
      ports:
        - "3306:3306"
      environment:
          - MYSQL_ROOT_PASSWORD=airflow_pass
          - MYSQL_USER=airflow
          - MYSQL_PASSWORD=airflow_pass
          - MYSQL_DATABASE=airflow
      volumes:
          - ./conf/cm-cicada/_airflow/create_airflow_db.sql:/docker-entrypoint-initdb.d/create_airflow_db.sql
          - ./data/cm-cicada/db_data:/var/lib/mysql

  # airflow-server
  # used by cm-cicada
  # See https://github.com/cloud-barista/cm-cicada/blob/main/_airflow/docker-compose.yml
  airflow-server:
      # build:
      #     context: ./conf/cm-cicada/_airflow ## build Docker file location
      container_name: airflow-server
      # image: airflow-server:2.9.1
      image: cloudbaristaorg/airflow-server:edge
      restart: always
      ports:
          - "5555:5555"
          - "8080:8080"
      command: >
          /bin/bash -c "
              # Wait for MySQL
              sleep 10

              # Clean up pid
              rm -f airflow-webserver.pid

              # Set up metadata database
              airflow db upgrade

              # Create default user
              airflow users create --username airflow --password airflow_pass --email ish@innogrid.com --firstname SuHyeon --lastname Im --role Admin

              # Start airflow
              airflow scheduler &
              airflow celery worker &
              airflow celery flower &
              airflow webserver

              # Keep the server on no matter what
              sleep infinity
          "
      depends_on:
          - airflow-mysql
      volumes:
              - ./conf/cm-cicada/_airflow/airflow-home:/usr/local/airflow
              - /var/run/docker.sock:/var/run/docker.sock
```

오늘 [conf/docker/conf/cm-cicada/_airflow/requirements.txt](https://github.com/cloud-barista/cm-mayfly/blob/-/conf/docker/conf/cm-cicada/_airflow/requirements.txt) 파일에 https://github.com/cloud-barista/cm-mayfly/security/dependabot/4 보안 이슈가 발생했으며 cm-cicada의 경우 4시간 전에 패치된 것을 확인했습니다만...
cm-cicada의 Docker 파일들과 docker-compose.yaml 파일들을 살펴 봐도 현재 [도커 이미지 기반으로 실행되는 방식](https://github.com/cloud-barista/cm-mayfly/issues/17)에서 해당 파일이 사용되는 컨테이너 이미지를 모르겠네요.^^;;;

[docker-compose.yaml](https://github.com/cloud-barista/cm-mayfly/blob/main/conf/docker/docker-compose.yaml) 파일 검토 후 [_airflow](https://github.com/cloud-barista/cm-mayfly/tree/main/conf/docker/conf/cm-cicada/_airflow) 폴더에서 불 필요한 삭제될 파일을 알려 주시면 감사하겠습니다.^^
